# Generated by Django 5.1.7 on 2025-04-20 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_borrower_user_borrowerprofile'),
        ('loans', '0002_alter_loanapplication_approved_by_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Borrower',
        ),
    ]
