# Generated by Django 4.2.20 on 2025-04-27 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_mfi_borrowerprofile_mfi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='borrowerprofile',
            name='mfi',
        ),
        migrations.DeleteModel(
            name='MFI',
        ),
    ]
