# Generated by Django 5.1.7 on 2025-04-19 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CreditRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrower_id', models.CharField(max_length=50)),
                ('mfi_id', models.CharField(max_length=50)),
                ('loan_history', models.JSONField(default=list)),
                ('default_count', models.IntegerField(default=0)),
                ('total_loans', models.IntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'credit_records',
            },
        ),
    ]
